spring.application.name=exocart

spring.datasource.url=jdbc:mysql://localhost:3306/exocart_db
spring.datasource.username=root
spring.datasource.password=Raaji@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajiankem0410@gmail.com
spring.mail.password=jdvxgofuxwldxokt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true